### PR TITLE
[RFR] New article - prop checks

### PR DESCRIPTION
**Pull request by eschaefer**
A quick overview of the power of `propTypes` in React. Let me know if anything seems unclear, or if anything should be added!

### CODE REVIEW

**Comment by eschaefer** [comment]
@HugoGiraudel @marcohamersma @smartmike

**Comment by HugoGiraudel** [comment]
I added some very minor improvements. Great article! Maybe just missing a conclusion?

**Comment by eschaefer** [comment]
Thanks Hugo! Added a conclusion.

**Comment by marcohamersma** [comment]
Nice stuff :)

**Comment by peterjmag** [comment]
Yeah, great post! Reminded me that I still need to add propTypes to the stuff I'm working on right now... :blush:

**Comment by eschaefer** [comment]
thx @marcohamersma @peterjmag !

**Pull request merged**
